### ISSUE TITLE
There was a problem parsing the package in Android 13

### ISSUE THREAD

**Issue by AntarCrypto** [samahmed/KillAppNow#1]
![Screenshot_20240108-100450_Package_installer](https://github.com/samahmed/KillAppNow/assets/135796323/f2cd7553-ef14-4ad3-8d47-35e1eb06ddb2)

**Comment by samahmed** [comment]
This version is compatible with Android 14+. For A13 and lower, GravityBox works for this feature.

**Comment by zakicade55** [comment]
> This version is compatible with Android 14+. For A13 and lower, GravityBox works for this feature.

Actually I'm using this version on Android 13. I just lowered the required android version from 14 to 13 and it worked.i am killing apps now by just long pressing the back button.😀
